### ISSUE TITLE
Can commit-updated-env be optional in push-pull-main? 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/actions#31]

**Comment by liamhuber** [comment]
What do you mean by optional?

There are some tools (binder and readthedocs) that use their own environment files. This job makes sure that whenever the core environment.yml is updated, that these downstream ends are updated -- ie there is a single point of contact for devs and the rest of the envs are automatically managed. Is there an alternative pattern you have in mind?

**Comment by jan-janssen** [comment]
I am just saying it is not the pattern used for the main pyiron packages like `pyiron_base`, `pyiron_atomistics`, ...

**Comment by liamhuber** [comment]
Yes, this pattern is better.

`pyiron_base` has, e.g. `.ci_support/environment.yml` and `.ci_support/environment-docs.yml`, and when a dev adds a module to the main `environment.yml` dependency list, they need to remember to *also* add it to the docs env manually, or the docs will break.

This new pattern removes the human from the equation. If someone goes out of their way to update the other envs it shouldn't hurt anything, but they are no longer required to remember it. This is a worthwhile change.

**Comment by jan-janssen** [comment]
No in the old version the environments are merged on the fly. This allows for specific dependencies for the docs which might not be required for the unit tests:
https://github.com/pyiron/pyiron_base/blob/main/.github/workflows/docs.yml#L20

**Comment by liamhuber** [comment]
Ah, TIL. Then why is the `environment-docs.yml` cluttered with a bunch of packages??

Here we are also [using condamerge.py](https://github.com/pyiron/actions/blob/12f70d3dd08cbe28aaf791e74313e62491331d70/write-environment/action.yml#L22), but the extra stuff needed for docs/notebooks/etc [is pulled from the pyiron/actions .support](https://github.com/pyiron/actions/blob/12f70d3dd08cbe28aaf791e74313e62491331d70/write-docs-env/action.yaml#L11) file, so that unless you need something _extra_ on top of that, you never even need to worry about adding the docs env file to your repo to start with. Thus, if we want to update the standard imports for all our docs([e.g.](https://github.com/pyiron/actions/blob/main/.support/environment-docs.yml)/binder/etc at once, we do it here in .support.

The old way requires less human input than I thought (although as evidenced by the cluttered docs env in base, humans can still get in and muddle it up?), but this is both more automated and gives us a place for centralized updates, so IMO it's still an improvement we should keep.

**Comment by liamhuber** [comment]
> This allows for specific dependencies for the docs which might not be required for the unit tests:

Note: the workflow here also allows for this, that's what the `docs/notebooks/tests-env-files:` variables in [`commit-updated-env`](https://github.com/pyiron/actions/blob/12f70d3dd08cbe28aaf791e74313e62491331d70/.github/workflows/push-pull-main.yml#L41) are -- they allow for any repo-specific (beyond those from the centralized pyiron/actions source) + application specific (beyond running the library).
